version: '3'
services: 
  server:
    image: "docker.io/library/nginx:mainline"
    ports: 
      - 8080:80
    volumes:
      - ./www:/srv/www:z
      - ./nginx.default.conf:/etc/nginx/nginx.conf:z
    networks: 
      - my-network
  phpfpm:
    image: "docker.io/library/php:7.4-fpm"
    volumes: 
      - ./www:/srv/www:z
    networks: 
      - my-network
networks: 
  my-network:
